# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

replicas: 1

controller:
  image:
    registry: ""
    repository: atomix/raft-controller
    # TODO: Set image tag to release version
    tag: latest
    # TODO: Revert pull policy to default for patch releases or Always for for minor releases
    pullPolicy: IfNotPresent
    pullSecrets: []

node:
  image:
    registry: ""
    repository: atomix/raft-node
    # TODO: Set image tag to release version
    tag: latest
    # TODO: Revert pull policy to default for patch releases or Always for for minor releases
    pullPolicy: IfNotPresent
    pullSecrets: []
