# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Parse and Validate Version

inputs:
  tag:
    description: 'The release tag'
    required: true

outputs:
  version:
    description: 'The parsed version'
    value: ${{ steps.parse-version.outputs.version }}

runs:
  using: composite
  steps:
    - id: parse-version
      name: Parse version
      shell: bash
      run: |
        version=$(basename "${{ inputs.tag }}")
        echo "version=${version/#v}" >> $GITHUB_OUTPUT
    # TODO: Validate the version