name: Release Controller

on:
  push:
    tags:
      - 'controller/v*'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Release
        uses: ./.github/actions/module/release
        with:
          working-directory: controller
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}