# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test Controller

on:
  push:
    branches:
      - 'master'
    paths:
      - 'controller/**'
  pull_request:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Go tests
        uses: ./.github/actions/go/test
        with:
          component: controller

      - name: Build init image
        uses: ./.github/actions/docker/build
        with:
          component: controller
          file: build/init/Dockerfile

      - name: Build controller image
        uses: ./.github/actions/docker/build
        with:
          component: controller
          file: build/controller/Dockerfile

      - name: Test Helm chart
        uses: ./.github/actions/helm/test
        with:
          component: controller
