# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: atomix-sidecar-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
      - configmaps
      - events
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - atomix.io
    resources:
      - '*'
    verbs:
      - '*'