# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: atomix-sidecar-controller
webhooks:
  - name: injector.sidecar.atomix.io
    # Match only pods that opt-in to Atomix with the sidecar.atomix.io/inject label
    objectSelector:
      matchLabels:
        sidecar.atomix.io/inject: "true"
    rules:
      # TODO: Support UPDATE operations for pods
      - operations: [ "CREATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
        scope: Namespaced
    clientConfig:
      service:
        name: atomix-sidecar-controller
        namespace: {{ .Release.Namespace }}
        path: /inject-sidecar
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRExGUzZuR3I1YmF6QU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05Nak13TVRJNU1ESXlPRE01V2hnUE1qSTVOakV4TVRNd01qSTRNemxhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU1vbW02ME1KL0g4UUk5ajlNYXBKbERBYTg4OGdrcFlaZjFKNlZZdHhZS2o4eDdGWEVuK2JLSU4KQytvQjBkaDBOZk1lRlREYnBtMFdVNmh1RG02eEdqb2hPYllCRnRJZ20rS2hPa24vdlM1Ylh4Ty9jMEdPd3EwNQphNmpiaGhsUUw2WTg3a3FUNFFuNXBBLy9RMzlpSmlBbU9YS3FIa1BzQjZCK1Fua0ZCemI5d3FmaWY1TFBYN3g0CjY0UnBVRjVLSERqOEhieXlLd2JRYXJzTG5JWFlydzlSRHlrVzFQVEMvaVlsdkdEenY2TWpyOE5SQkdpenZ6SncKZ0cvcUdQN0pWb1lRYUMySXZSSjNSSTdLekZzVzBYRE9aSEdKWUFEQkZNMjJOZkhKNVBBZjU1dXZEa0hEY2dSagpSbmxuU2lvbkJtSmRFNzVXc2wvcVdKVlplbGZ6dXBrQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCmlIVURlTDVWeEdjTmdveGJHWmpqbysrK2pnK28xQXpweHV4M2V3Q2J2UVRhK21JZ2pMZ1FhbkVQM1VMRzlQTUMKOERJWnVXUFZuU3B0bUNVeFNyNEdmcHpNeUJjUXFDSjNoREo5allsR3oxRUVkT3Q1SnloUUVoRXhXSW8wMGRSRQpIeXBoaERXdzVWcjhRZ0pJNU0yaER1NzRtUk5lcXAzMjRaY054V3ZEakZ2Z3dWMG9kSDFTQnFqR29taFZ5c1lqCjlHT1IwOXNKOVMzZlBxQngrTXhDeWdrUFpua0RFeW9zaC9pQk95ZUd6VlhjalNPeFRYSFlDVFhnM1lZQ05NRVEKNjBPT09nQWdTZDRWUVc1MzRWenVteGNNb29SRHMyTUlkbXNzZjBoQ0Rhek9YMHBqSVNUa2xwUVp3dWVaa1VJbApOOUlIOHB4Mjh6LzByODNXR3ZxSTZnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    admissionReviewVersions: [ "v1beta1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10