# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Release Benchmarking Tool

on:
  push:
    tags:
      - 'bench/v*'

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-release

jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish Docker image
        uses: ./.github/actions/docker/publish
        with:
          component: bench
          file: build/Dockerfile
          repository: atomix/bench
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Helm chart
        uses: ./.github/actions/helm/publish
        with:
          component: bench
