# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Release Benchmark Tool

on:
  push:
    tags:
      - 'bench/v*'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        uses: ./.github/actions/go/test
        with:
          path: bench

      - name: Build Docker image
        uses: ./.github/actions/docker/build
        with:
          path: bench
          dockerfile: build/Dockerfile
          repository: atomix/bench

      - name: Publish Docker image
        uses: ./.github/actions/docker/publish
        with:
          repository: atomix/bench
          tag: ${{ github.ref_name }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
