# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test Benchmarking Tool

on:
  push:
    branches:
      - 'master'
    paths:
      - 'bench/**'
  pull_request:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Go tests
        uses: ./.github/actions/go/test
        with:
          path: bench

      - name: Build Docker image
        uses: ./.github/actions/docker/build
        with:
          path: bench
          dockerfile: build/Dockerfile

      - name: Test Helm chart
        uses: ./.github/actions/helm/test
        with:
          path: bench/chart
