name: Verify Benchmarks

on:
  push:
    branches:
      - 'master'
    paths:
      - 'bench/**'
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Verify
        uses: ./.github/actions/module/verify.yml
        with:
          working-directory: bench
