# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Publish Helm Chart

inputs:
  path:
    description: 'The chart path relative to the repository root'
    required: true

  version:
    description: 'The release version'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR"

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0

    - name: Package Helm chart
      run: |
        helm package ${{ inputs.path }} \
          --version ${{ inputs.version }} \
          --app-version "v${{ inputs.version }}" \
          --destination .deploy
      shell: bash

    - name: Publish Helm chart
      uses: helm/chart-releaser-action@v1.5.0
      with:
        skip_packaging: true
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CR_PACKAGE_PATH: .deploy
        CR_SKIP_EXISTING: true
