# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: profiles.storage.atomix.io
spec:
  group: storage.atomix.io
  scope: Namespaced
  names:
    kind: Profile
    listKind: ProfileList
    plural: profiles
    singular: profile
  versions:
    - name: v3beta2
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the profile.
              type: object
              required:
                - bindings
              properties:
                proxy:
                  type: object
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                      enum:
                        - Never
                        - IfNotPresent
                        - Always
                    securityContext:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    logging:
                      type: object
                      properties:
                        loggers:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              level:
                                type: string
                                nullable: true
                                enum:
                                  - debug
                                  - info
                                  - warn
                                  - error
                                  - fatal
                                  - panic
                              output:
                                type: object
                                additionalProperties:
                                  type: object
                                  properties:
                                    sink:
                                      type: string
                                    level:
                                      type: string
                                      nullable: true
                                      enum:
                                        - debug
                                        - info
                                        - warn
                                        - error
                                        - fatal
                                        - panic
                        sinks:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              encoding:
                                type: string
                                nullable: true
                                enum:
                                  - console
                                  - json
                              stdout:
                                type: object
                              stderr:
                                type: object
                              file:
                                type: object
                                properties:
                                  path:
                                    type: string
                                required:
                                  - path
                bindings:
                  type: array
                  items:
                    type: object
                    required:
                      - store
                    properties:
                      store:
                        type: object
                        required:
                          - name
                        properties:
                          namespace:
                            type: string
                          name:
                            type: string
                      priority:
                        type: integer
                        minimum: 0
                        default: 0
                      selector:
                        type: object
                        additionalProperties:
                          type: string
                      services:
                        type: array
                        items:
                          type: object
                          required:
                            - name
                          properties:
                            name:
                              type: string
                            config:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                podStatuses:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                      proxy:
                        type: object
                        properties:
                          ready:
                            type: boolean
                          bindings:
                            type: array
                            items:
                              type: object
                              required:
                                - store
                              properties:
                                store:
                                  type: object
                                  required:
                                    - name
                                  properties:
                                    name:
                                      type: string
                                    namespace:
                                      type: string
                                ready:
                                  type: boolean
                                version:
                                  type: string
      additionalPrinterColumns: []