# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: profiles.storage.atomix.io
spec:
  group: storage.atomix.io
  scope: Namespaced
  names:
    kind: Profile
    listKind: ProfileList
    plural: profiles
    singular: profile
  versions:
    - name: v3beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the profile.
              type: object
              required:
                - routes
              properties:
                routes:
                  type: array
                  items:
                    type: object
                    required:
                      - store
                      - bindings
                    properties:
                      store:
                        type: object
                        required:
                          - name
                        properties:
                          namespace:
                            type: string
                          name:
                            type: string
                      bindings:
                        type: array
                        items:
                          type: object
                          required:
                            - matchRules
                          properties:
                            services:
                              type: array
                              items:
                                type: object
                                required:
                                  - name
                                properties:
                                  name:
                                    type: string
                                  config:
                                    type: object
                                    x-kubernetes-preserve-unknown-fields: true
                            matchRules:
                              type: array
                              items:
                                type: object
                                properties:
                                  names:
                                    type: array
                                    items:
                                      type: string
                                  tags:
                                    type: object
                                    additionalProperties:
                                      type: string
      additionalPrinterColumns: [ ]