# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: proxies.storage.atomix.io
spec:
  group: storage.atomix.io
  scope: Namespaced
  names:
    kind: Proxy
    listKind: ProxyList
    plural: proxies
    singular: proxy
  versions:
    - name: v3beta1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          required:
            - pod
            - profile
          properties:
            pod:
              description: |-
                The pod object reference.
              type: object
              required:
                - name
              properties:
                name:
                  type: string
            profile:
              description: |-
                The profile object reference.
              type: object
              required:
                - name
              properties:
                name:
                  type: string
            status:
              type: object
              properties:
                ready:
                  type: boolean
                routes:
                  type: array
                  items:
                    type: object
                    required:
                      - store
                    properties:
                      store:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                      state:
                        type: string
                        default: Pending
                        enum:
                          - Pending
                          - Connected
                      version:
                        type: string
