name: Release Module
inputs:
  working-directory:
    description: 'The working directory'
    required: true
    default: ''
  docker-username:
    description: 'The Docker username'
    required: true
  docker-password:
    description: 'The Docker password'
    required: true
runs:
  using: composite
  steps:
    - name: Verify
      uses: ./.github/actions/module/verify
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Release
      run: make release
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        TAG: ${{ github.ref_name }}