# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test Shared Memory Driver

on:
  push:
    branches:
      - 'master'
    tags:
      - 'drivers/shared-memory/v*'
    paths:
      - 'drivers/shared-memory/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test shared-memory@v1
        uses: ./.github/actions/go/test
        with:
          path: drivers/shared-memory
          package: github.com/atomix/atomix/drivers/shared-memory/driver/...
