apiVersion: atomix.io/v3beta1
kind: Profile
metadata:
  name: example-profile
  namespace: default
spec:
  routes:
    - store:
        namespace: default
        name: example-store
      bindings:
        - services:
            - name: atomix.runtime.map.v1.Map
              config:
                cache:
                  enabled: true
          matchRules:
            - names:
                - '*'
              tags:
                foo: bar
                bar: baz
