apiVersion: storage.atomix.io/v3beta2
kind: Profile
metadata:
  name: example-profile
  namespace: default
spec:
  bindings:
    - store:
        name: example-store
      priority: 1
      selector:
        foo: bar
        bar: baz
      services:
        - name: atomix.runtime.map.v1.Map
          config:
            cache:
              enabled: true
