apiVersion: atomix.io/v3beta3
kind: StorageProfile
metadata:
  name: example-profile
  namespace: default
spec:
  bindings:
    - store:
        name: example-store
      priority: 1
      tags:
        - foo
        - bar
      services:
        - name: atomix.runtime.map.v1.Map
          config:
            cache:
              enabled: true
