apiVersion: conformance.atomix.io/v3beta1
kind: TestCase
metadata:
  name: example-conformance-test
  namespace: default
driver:
  name: multi-raft
  version: v1beta1
service: atomix.runtime.map.v1.Map
config:
  cache:
    enabled: false
status:
  state: Running | Passed | Failed
