# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Verify Pod Memory Driver

on:
  push:
    branches:
      - 'master'
    tags:
      - 'drivers/pod-memory/v*'
    paths:
      - 'drivers/pod-memory/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        uses: ./.github/actions/go/test
        with:
          path: drivers/pod-memory
          package: github.com/atomix/atomix/drivers/pod-memory/driver/...
