# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Verify Redis v9 Driver

on:
  push:
    branches:
      - 'master'
    tags:
      - 'drivers/redis/v9/v*'
    paths:
      - 'drivers/redis/v9/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check plugin compatibility
        uses: ./.github/actions/driver/check-compatibility
        with:
          path: drivers/redis/v9

      - name: Run tests
        uses: ./.github/actions/go/test
        with:
          path: drivers/redis/v9
          package: github.com/atomix/atomix/drivers/redis/v9/driver/...
