name: Verify Module
inputs:
  working-directory:
    description: 'The working directory'
    required: true
    default: ''
runs:
  using: composite
  steps:
    - name: Build
      uses: .github/actions/module/build.yml
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Test
      uses: .github/actions/module/test.yml
      with:
        working-directory: ${{ inputs.working-directory }}
