# Create a SharedMemoryStore for storing primitive state
apiVersion: sharedmemory.atomix.io/v1beta1
kind: SharedMemoryStore
metadata:
  name: basic-example-store
---
# Create a StorageProfile to bind your application to the store
apiVersion: atomix.io/v3beta3
kind: StorageProfile
metadata:
  name: basic-example
spec:
  bindings:
    - store:
        name: basic-example-store
---
# Create a Deployment annotating the pods to use the StorageProfile
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-example
  labels:
    app: basic-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-example
  template:
    metadata:
      labels:
        app: basic-example
      annotations:
        # Inject the proxy into the pods
        proxy.atomix.io/inject: "true"
        # Configure the proxy to use the basic-example profile
        proxy.atomix.io/profile: basic-example
    spec:
      containers:
        - name: sleep
          image: alpine:latest
          command: ["/bin/sh", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
