# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Publish Atomix Helm Chart

on:
  push:
    branches:
      - 'master'
    paths:
      - 'charts/atomix/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish
        uses: ./.github/actions/chart/publish
        with:
          path: charts/atomix
          token: ${{ secrets.GH_TOKEN }}
