name: Publish Atomix Helm Chart

on:
  push:
    branches:
      - 'master'
    paths:
      - 'charts/atomix/**'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish
        uses: ./.github/actions/chart/publish
        with:
          working-directory: charts/atomix
          github-token: ${{ secrets.GH_TOKEN }}
