# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: atomix
description: Chart for deploying Atomix with storage various controllers
kubeVersion: ">=1.17.0"
type: application
version: 2.0.0
keywords:
- atomix
home: https://atomix.io
maintainers:
- name: Jordan Halterman
  email: jordan.halterman@intel.com
dependencies:
  - name: atomix-controller
    version: 2.0.0
    alias: controller
  - name: atomix-raft-controller
    version: 2.0.0
    condition: raft.enabled
    alias: raft
  - name: atomix-shared-memory-controller
    version: 2.0.0
    condition: shared-memory.enabled
    alias: shared-memory
  - name: atomix-pod-memory-controller
    version: 2.0.0
    condition: pod-memory.enabled
    alias: pod-memory
  - name: atomix-consensus-controller
    version: 1.5.1
    repository: https://charts.atomix.io
    condition: consensus.enabled
    alias: consensus-controller
