# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

multi-raft:
  enabled: true
  nameOverride: multi-raft-controller
shared-memory:
  enabled: true
  nameOverride: shared-memory-controller
pod-memory:
  enabled: true
  nameOverride: pod-memory-controller
