# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

raft:
  enabled: true
  nameOverride: raft-controller
shared-memory:
  enabled: true
  nameOverride: shared-memory-controller
pod-memory:
  enabled: true
  nameOverride: pod-memory-controller
consensus:
  enabled: true
  nameOverride: consensus-controller
