# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datastores.atomix.io
spec:
  group: atomix.io
  scope: Namespaced
  names:
    kind: DataStore
    listKind: DataStoreList
    plural: datastores
    singular: datastore
    shortNames:
      - ds
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: [ "v1" ]
      clientConfig:
        service:
          name: atomix-controller
          namespace: kube-system
          path: /convert-data-store
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRHJlaXcyZHg3dHVEQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05Nak13TVRJNE1EWXpNekl5V2hnUE1qSTVOakV4TVRJd05qTXpNakphTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUx2N2RnV0k3NE4vU215K0tyeDlpRGdLQzMrR2pUcngycklvSEFqbEhKU3ZrYUxiZEVqWkRmMnUKRHgvODFkOWlxd3pOY0FFcGpQMVNCRzVKUE1KcWVEa2EwbEMweEMxbGxlY2Y4TjcvSVRLVmR2V3R3UGgvR1hGaQpiU1JXMVhnNTFxZ2xtN3ZXYlRyUk4vdXlPSHZQNkE2R1M4UFA2Z3V1UkpJYU1QQlN3UUtVTEZDVXI4aVVoUENzCjhiQVdSbXZDUVNDeXoxV0tISGNVbEhRQ2RpSHdQWDZ3Sm9jRXl3VTZlU1ZoMWdqemlKeXY4MGJMdFVHc1VtQXMKV2N1VmkrRzUwblZ0bmYrN2szU2xhcGxyRUxOYXJvOWdud0UrQVJ4SXdvZDBudW5FcVNEVUZGSlBXWkJMSjFndApXNEZNd2tCcFFMVy8wV0dlSFdWdjdzbEJQLzIzMEEwQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCkszSXpkNmwreHNXWTFlejZGODFJMTdCU2sxWWl6bzZmM1dJWmFBZUtncmVKSUJOZ2JwZTd3RlAvOWZNSG9aa3EKTjhLemtmK3JlbThVVU4wWm5DOEwyQnFHYmRaeVNBeUJYcElGS3pJTnVYR3FDUVo4ZHJtNUsvM2FpWjhSK1VZVwoxSWFuT1l5bDBSR1pMRExXVFJQNWdaZzk3TTRZQlpDVkVPZlFwZnhtenZPbXAxekhrVmVacDFzRTBwN2ZxbUpwCjFCNUw4ZHFZbTRvQ0g3VzZtZUNzZFRtME1FUmlYWDQxcG1zQUZCVVo5UnVLcElDZzdkTDlES2xHbWs2VFdnbGkKcURyVGJaNUR4S0xwVTg0Rk5ZR1RNZWhySE5HSVJQbE5VUjVlODhDS3BVN29pYzBwOUh1VEEvVi9YK1lpWWZuegpUNkNHSk5PZkkwZzRoT0ViRDdBUU1nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  versions:
    - name: v3beta3
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the store.
              type: object
              required:
                - driver
              properties:
                driver:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    version:
                      type: string
                config:
                  description: |-
                    The configuration for the runtime driver.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Driver
          type: string
          description: The name of the driver used to access the store
          jsonPath: .spec.driver.name
        - name: API Version
          type: string
          description: The driver API version
          jsonPath: .spec.driver.apiVersion
    - name: v3beta4
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the store.
              type: object
              required:
                - driver
              properties:
                driver:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    apiVersion:
                      type: string
                config:
                  description: |-
                    The configuration for the runtime driver.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Driver
          type: string
          description: The name of the driver used to access the store
          jsonPath: .spec.driver.name
        - name: API Version
          type: string
          description: The driver API version
          jsonPath: .spec.driver.apiVersion
