# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datastores.atomix.io
spec:
  group: atomix.io
  scope: Namespaced
  names:
    kind: DataStore
    listKind: DataStoreList
    plural: datastores
    singular: datastore
    shortNames:
      - ds
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: [ "v1" ]
      clientConfig:
        service:
          name: atomix-controller
          namespace: kube-system
          path: /convert-data-store
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRExGUzZuR3I1YmF6QU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05Nak13TVRJNU1ESXlPRE01V2hnUE1qSTVOakV4TVRNd01qSTRNemxhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU1vbW02ME1KL0g4UUk5ajlNYXBKbERBYTg4OGdrcFlaZjFKNlZZdHhZS2o4eDdGWEVuK2JLSU4KQytvQjBkaDBOZk1lRlREYnBtMFdVNmh1RG02eEdqb2hPYllCRnRJZ20rS2hPa24vdlM1Ylh4Ty9jMEdPd3EwNQphNmpiaGhsUUw2WTg3a3FUNFFuNXBBLy9RMzlpSmlBbU9YS3FIa1BzQjZCK1Fua0ZCemI5d3FmaWY1TFBYN3g0CjY0UnBVRjVLSERqOEhieXlLd2JRYXJzTG5JWFlydzlSRHlrVzFQVEMvaVlsdkdEenY2TWpyOE5SQkdpenZ6SncKZ0cvcUdQN0pWb1lRYUMySXZSSjNSSTdLekZzVzBYRE9aSEdKWUFEQkZNMjJOZkhKNVBBZjU1dXZEa0hEY2dSagpSbmxuU2lvbkJtSmRFNzVXc2wvcVdKVlplbGZ6dXBrQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCmlIVURlTDVWeEdjTmdveGJHWmpqbysrK2pnK28xQXpweHV4M2V3Q2J2UVRhK21JZ2pMZ1FhbkVQM1VMRzlQTUMKOERJWnVXUFZuU3B0bUNVeFNyNEdmcHpNeUJjUXFDSjNoREo5allsR3oxRUVkT3Q1SnloUUVoRXhXSW8wMGRSRQpIeXBoaERXdzVWcjhRZ0pJNU0yaER1NzRtUk5lcXAzMjRaY054V3ZEakZ2Z3dWMG9kSDFTQnFqR29taFZ5c1lqCjlHT1IwOXNKOVMzZlBxQngrTXhDeWdrUFpua0RFeW9zaC9pQk95ZUd6VlhjalNPeFRYSFlDVFhnM1lZQ05NRVEKNjBPT09nQWdTZDRWUVc1MzRWenVteGNNb29SRHMyTUlkbXNzZjBoQ0Rhek9YMHBqSVNUa2xwUVp3dWVaa1VJbApOOUlIOHB4Mjh6LzByODNXR3ZxSTZnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  versions:
    - name: v3beta3
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the store.
              type: object
              required:
                - driver
              properties:
                driver:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    version:
                      type: string
                config:
                  description: |-
                    The configuration for the runtime driver.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Driver
          type: string
          description: The name of the driver used to access the store
          jsonPath: .spec.driver.name
        - name: API Version
          type: string
          description: The driver API version
          jsonPath: .spec.driver.apiVersion
    - name: v3beta4
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the store.
              type: object
              required:
                - driver
              properties:
                driver:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    apiVersion:
                      type: string
                config:
                  description: |-
                    The configuration for the runtime driver.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Driver
          type: string
          description: The name of the driver used to access the store
          jsonPath: .spec.driver.name
        - name: API Version
          type: string
          description: The driver API version
          jsonPath: .spec.driver.apiVersion
