# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storageprofiles.atomix.io
spec:
  group: atomix.io
  scope: Namespaced
  names:
    kind: StorageProfile
    listKind: StorageProfileList
    plural: storageprofiles
    singular: storageprofile
    shortNames:
      - profiles
      - profile
      - sp
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: [ "v1" ]
      clientConfig:
        service:
          name: atomix-controller
          namespace: kube-system
          path: /convert-storage-profile
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRHJlaXcyZHg3dHVEQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05Nak13TVRJNE1EWXpNekl5V2hnUE1qSTVOakV4TVRJd05qTXpNakphTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUx2N2RnV0k3NE4vU215K0tyeDlpRGdLQzMrR2pUcngycklvSEFqbEhKU3ZrYUxiZEVqWkRmMnUKRHgvODFkOWlxd3pOY0FFcGpQMVNCRzVKUE1KcWVEa2EwbEMweEMxbGxlY2Y4TjcvSVRLVmR2V3R3UGgvR1hGaQpiU1JXMVhnNTFxZ2xtN3ZXYlRyUk4vdXlPSHZQNkE2R1M4UFA2Z3V1UkpJYU1QQlN3UUtVTEZDVXI4aVVoUENzCjhiQVdSbXZDUVNDeXoxV0tISGNVbEhRQ2RpSHdQWDZ3Sm9jRXl3VTZlU1ZoMWdqemlKeXY4MGJMdFVHc1VtQXMKV2N1VmkrRzUwblZ0bmYrN2szU2xhcGxyRUxOYXJvOWdud0UrQVJ4SXdvZDBudW5FcVNEVUZGSlBXWkJMSjFndApXNEZNd2tCcFFMVy8wV0dlSFdWdjdzbEJQLzIzMEEwQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCkszSXpkNmwreHNXWTFlejZGODFJMTdCU2sxWWl6bzZmM1dJWmFBZUtncmVKSUJOZ2JwZTd3RlAvOWZNSG9aa3EKTjhLemtmK3JlbThVVU4wWm5DOEwyQnFHYmRaeVNBeUJYcElGS3pJTnVYR3FDUVo4ZHJtNUsvM2FpWjhSK1VZVwoxSWFuT1l5bDBSR1pMRExXVFJQNWdaZzk3TTRZQlpDVkVPZlFwZnhtenZPbXAxekhrVmVacDFzRTBwN2ZxbUpwCjFCNUw4ZHFZbTRvQ0g3VzZtZUNzZFRtME1FUmlYWDQxcG1zQUZCVVo5UnVLcElDZzdkTDlES2xHbWs2VFdnbGkKcURyVGJaNUR4S0xwVTg0Rk5ZR1RNZWhySE5HSVJQbE5VUjVlODhDS3BVN29pYzBwOUh1VEEvVi9YK1lpWWZuegpUNkNHSk5PZkkwZzRoT0ViRDdBUU1nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  versions:
    - name: v3beta3
      served: true
      storage: false
      deprecated: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the profile.
              type: object
              required:
                - bindings
              properties:
                proxy:
                  type: object
                  default: {}
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                      enum:
                        - Never
                        - IfNotPresent
                        - Always
                    securityContext:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    logging:
                      type: object
                      default: {}
                      properties:
                        encoding:
                          type: string
                          default: console
                          enum:
                            - console
                            - json
                        rootLevel:
                          type: string
                          default: info
                          enum:
                            - debug
                            - info
                            - warn
                            - error
                            - fatal
                            - panic
                        loggers:
                          type: array
                          items:
                            type: object
                            required:
                              - name
                            properties:
                              name:
                                type: string
                              level:
                                type: string
                                nullable: true
                                enum:
                                  - debug
                                  - info
                                  - warn
                                  - error
                                  - fatal
                                  - panic
                bindings:
                  type: array
                  items:
                    type: object
                    required:
                      - store
                    properties:
                      store:
                        type: object
                        required:
                          - name
                        properties:
                          namespace:
                            type: string
                          name:
                            type: string
                      priority:
                        type: integer
                        minimum: 0
                        default: 0
                      tags:
                        type: array
                        items:
                          type: string
                      primitives:
                        type: array
                        items:
                          type: object
                          required:
                            - kind
                            - apiVersion
                          properties:
                            kind:
                              type: string
                            apiVersion:
                              type: string
                            name:
                              type: string
                            tags:
                              type: array
                              items:
                                type: string
                            config:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                podStatuses:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - uid
                      - resourceVersion
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      uid:
                        type: string
                      resourceVersion:
                        type: string
                      proxy:
                        type: object
                        properties:
                          routes:
                            type: array
                            items:
                              type: object
                              required:
                                - store
                              properties:
                                store:
                                  type: object
                                  required:
                                    - name
                                  properties:
                                    name:
                                      type: string
                                    namespace:
                                      type: string
                                state:
                                  type: string
                                  default: Pending
                                  enum:
                                    - Pending
                                    - Connecting
                                    - Connected
                                    - Configuring
                                    - Disconnecting
                                    - Disconnected
                                version:
                                  type: string
      additionalPrinterColumns: []
    - name: v3beta4
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the profile.
              type: object
              required:
                - routes
              properties:
                routes:
                  type: array
                  items:
                    type: object
                    required:
                      - store
                    properties:
                      store:
                        type: object
                        required:
                          - name
                        properties:
                          namespace:
                            type: string
                          name:
                            type: string
                      rules:
                        type: array
                        items:
                          type: object
                          properties:
                            kind:
                              type: string
                            apiVersion:
                              type: string
                            names:
                              type: array
                              items:
                                type: string
                            tags:
                              type: array
                              items:
                                type: string
                            config:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                podStatuses:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - uid
                      - resourceVersion
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      uid:
                        type: string
                      resourceVersion:
                        type: string
                      runtime:
                        type: object
                        properties:
                          routes:
                            type: array
                            items:
                              type: object
                              required:
                                - store
                              properties:
                                store:
                                  type: object
                                  required:
                                    - name
                                  properties:
                                    name:
                                      type: string
                                    namespace:
                                      type: string
                                state:
                                  type: string
                                  default: Pending
                                  enum:
                                    - Pending
                                    - Connecting
                                    - Connected
                                    - Configuring
                                    - Disconnecting
                                    - Disconnected
                                version:
                                  type: string
      additionalPrinterColumns: []