# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storageprofiles.atomix.io
spec:
  group: atomix.io
  scope: Namespaced
  names:
    kind: StorageProfile
    listKind: StorageProfileList
    plural: storageprofiles
    singular: storageprofile
    shortNames:
      - profiles
      - profile
      - sp
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: [ "v1" ]
      clientConfig:
        service:
          name: atomix-controller
          namespace: kube-system
          path: /convert-storage-profile
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRDBWM0JKM00rSzVEQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05Nak13TWpBeE1Ua3dNek01V2hnUE1qSTVOakV4TVRZeE9UQXpNemxhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU03WFNPM2QvRnB4dGVEakpuTkRPbktmL1B3TWNxQmtaVldPOVBiQU9HSForNlFwK0dkU2V3Nk8KQkZ0bkZab2dGdCtYK2dKQnBKdmdqQmNIUzRPYkE4QnFLdFUrU2pBWnQ5bzlLYzNGK2RBRWFxekYrcGY2YkRtcwpjSFcvRTFRcmovTTVlSEpzK2FGQjVxOFJjVlhJUEFjSzdMZmlxWFBYU3E5Vk9RcHJzK0xJRTU0SVRrbFhPVkRuClZiR3JkanFZZHVEMmJqL3BFanNUbG1KNk9KcWZYazVKRG5kaSt0QkkvM0thTkIwQ1VzZFBDV3VNRWlMYjJNeHYKdXBYOVZ3bk1sczk0Y1lXaGFiUVdwNW4rbzRMSDZvZzdKdmdvdzNXRFdVTFlCU1VsdjlORW5TYkRtL0NEUHdqNwo1SXc4cXdSRXpDeFBFV1VwMEhXcVdJd1ZHL0R3bWJFQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCkQreXRRTWNURzlhc1JJRCtxdm81S3pGWm8za2lJUWR5R09XS0VOampEcS9FeTFuTFNsdUx5b3Q1MG9DTmVOZ1AKc0p4NUZkTnprT0lDcGl3QUNLVlRKeWI3NUQzVDRYWi95b3Q1NUtaNHVaZXNaa2dMRENudjVFMDVvUFBqVmFiZQora3pscGp6bjBOcE1ZQUk1SGxKVmdEYXZ5SHUzeHJWbFF2ZTd0UTJaWkJZYzZraFZneUpwNTBDdkJYVVVqUVdnCngvejNEQW1hMmh6ZUZlSEVRNkVLbG95VHpmZDNrSGhiYUxWeEZFaGw0RDV4NFhRdzBSRndoWjVUcUpmMVB3S0UKeUNRUlRCTWU3a2RSMWxzcWFJUmFUY09ZZUx1d2R0QWFVbnc0aXFEUksrWjE3OE96UTVOT09nMUg0RUVkdzgwRQpEVjF2R3JUZXg0ZGxsOW9Mby9pVjR3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  versions:
    - name: v3beta3
      served: true
      storage: false
      deprecated: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the profile.
              type: object
              required:
                - bindings
              properties:
                proxy:
                  type: object
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                      enum:
                        - Never
                        - IfNotPresent
                        - Always
                    securityContext:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    config:
                      type: object
                      properties:
                        server:
                          type: object
                          properties:
                            readBufferSize:
                              type: integer
                              nullable: true
                            writeBufferSize:
                              type: integer
                              nullable: true
                            maxSendMsgSize:
                              type: string
                              nullable: true
                            maxRecvMsgSize:
                              type: string
                              nullable: true
                            numStreamWorkers:
                              type: integer
                              nullable: true
                            maxConcurrentStreams:
                              type: integer
                              nullable: true
                        logging:
                          type: object
                          properties:
                            loggers:
                              type: object
                              additionalProperties:
                                type: object
                                properties:
                                  level:
                                    type: string
                                    nullable: true
                                    enum:
                                      - debug
                                      - info
                                      - warn
                                      - error
                                      - fatal
                                      - panic
                                  output:
                                    type: object
                                    additionalProperties:
                                      type: object
                                      properties:
                                        sink:
                                          type: string
                                        level:
                                          type: string
                                          nullable: true
                                          enum:
                                            - debug
                                            - info
                                            - warn
                                            - error
                                            - fatal
                                            - panic
                            sinks:
                              type: object
                              additionalProperties:
                                type: object
                                properties:
                                  encoding:
                                    type: string
                                    nullable: true
                                    enum:
                                      - console
                                      - json
                                  stdout:
                                    type: object
                                  stderr:
                                    type: object
                                  file:
                                    type: object
                                    properties:
                                      path:
                                        type: string
                                    required:
                                      - path
                bindings:
                  type: array
                  items:
                    type: object
                    required:
                      - store
                    properties:
                      store:
                        type: object
                        required:
                          - name
                        properties:
                          namespace:
                            type: string
                          name:
                            type: string
                      priority:
                        type: integer
                        minimum: 0
                        default: 0
                      tags:
                        type: array
                        items:
                          type: string
                      services:
                        type: array
                        items:
                          type: object
                          required:
                            - name
                          properties:
                            name:
                              type: string
                            config:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                podStatuses:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - uid
                      - resourceVersion
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      uid:
                        type: string
                      resourceVersion:
                        type: string
                      proxy:
                        type: object
                        properties:
                          routes:
                            type: array
                            items:
                              type: object
                              required:
                                - store
                              properties:
                                store:
                                  type: object
                                  required:
                                    - name
                                  properties:
                                    name:
                                      type: string
                                    namespace:
                                      type: string
                                state:
                                  type: string
                                  default: Pending
                                  enum:
                                    - Pending
                                    - Connecting
                                    - Connected
                                    - Configuring
                                    - Disconnecting
                                    - Disconnected
                                version:
                                  type: string
      additionalPrinterColumns: []
    - name: v3beta4
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the profile.
              type: object
              required:
                - routes
              properties:
                routes:
                  type: array
                  items:
                    type: object
                    required:
                      - store
                    properties:
                      store:
                        type: object
                        required:
                          - name
                        properties:
                          namespace:
                            type: string
                          name:
                            type: string
                      rules:
                        type: array
                        items:
                          type: object
                          properties:
                            kind:
                              type: string
                            apiVersion:
                              type: string
                            names:
                              type: array
                              items:
                                type: string
                            tags:
                              type: array
                              items:
                                type: string
                            config:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                podStatuses:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - uid
                      - resourceVersion
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      uid:
                        type: string
                      resourceVersion:
                        type: string
                      runtime:
                        type: object
                        properties:
                          routes:
                            type: array
                            items:
                              type: object
                              required:
                                - store
                              properties:
                                store:
                                  type: object
                                  required:
                                    - name
                                  properties:
                                    name:
                                      type: string
                                    namespace:
                                      type: string
                                state:
                                  type: string
                                  default: Pending
                                  enum:
                                    - Pending
                                    - Connecting
                                    - Connected
                                    - Configuring
                                    - Disconnecting
                                    - Disconnected
                                version:
                                  type: string
      additionalPrinterColumns: []