# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storageprofiles.atomix.io
spec:
  group: atomix.io
  scope: Namespaced
  names:
    kind: StorageProfile
    listKind: StorageProfileList
    plural: storageprofiles
    singular: storageprofile
    shortNames:
      - profiles
      - profile
      - sp
  versions:
    - name: v3beta3
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the profile.
              type: object
              required:
                - bindings
              properties:
                proxy:
                  type: object
                  default: {}
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                      enum:
                        - Never
                        - IfNotPresent
                        - Always
                    securityContext:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    logging:
                      type: object
                      default: {}
                      properties:
                        encoding:
                          type: string
                          default: console
                          enum:
                            - console
                            - json
                        rootLevel:
                          type: string
                          default: info
                          enum:
                            - debug
                            - info
                            - warn
                            - error
                            - fatal
                            - panic
                        loggers:
                          type: array
                          items:
                            type: object
                            required:
                              - name
                            properties:
                              name:
                                type: string
                              level:
                                type: string
                                nullable: true
                                enum:
                                  - debug
                                  - info
                                  - warn
                                  - error
                                  - fatal
                                  - panic
                bindings:
                  type: array
                  items:
                    type: object
                    required:
                      - store
                    properties:
                      store:
                        type: object
                        required:
                          - name
                        properties:
                          namespace:
                            type: string
                          name:
                            type: string
                      priority:
                        type: integer
                        minimum: 0
                        default: 0
                      tags:
                        type: array
                        deprecated: true
                        items:
                          type: string
                      matchTags:
                        type: array
                        items:
                          type: string
                      primitives:
                        type: array
                        items:
                          type: object
                          required:
                            - kind
                            - apiVersion
                          properties:
                            kind:
                              type: string
                            apiVersion:
                              type: string
                            name:
                              type: string
                            tags:
                              type: array
                              deprecated: true
                              items:
                                type: string
                            matchTags:
                              type: array
                              items:
                                type: string
                            config:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                podStatuses:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - uid
                      - resourceVersion
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      uid:
                        type: string
                      resourceVersion:
                        type: string
                      proxy:
                        type: object
                        properties:
                          routes:
                            type: array
                            items:
                              type: object
                              required:
                                - store
                              properties:
                                store:
                                  type: object
                                  required:
                                    - name
                                  properties:
                                    name:
                                      type: string
                                    namespace:
                                      type: string
                                state:
                                  type: string
                                  default: Pending
                                  enum:
                                    - Pending
                                    - Connecting
                                    - Connected
                                    - Configuring
                                    - Disconnecting
                                    - Disconnected
                                version:
                                  type: string
      additionalPrinterColumns: []