# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Setup Helm

runs:
  using: composite
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        check-latest: true

    - name: Set up chart tests
      uses: helm/chart-testing-action@v2.3.1

    #- name: Create kind cluster
    #  uses: helm/kind-action@v1.4.0
