plugins:
  - name: MultiRaft
    version: v2beta1
    path: github.com/atomix/multi-raft-storage/driver@79deae5
  #- name: Gossip
  #  version: v1beta1
  #  path: github.com/atomix/gossip-storage/driver@d37ebcc
