plugins:
  - name: MultiRaft
    version: v1beta1
    path: github.com/atomix/multi-raft-storage/driver@8692853d829d5dfcc74f5a62beefad4752409a9b
  #- name: memory
  #  path: github.com/atomix/drivers/memory
  #  version: latest