plugins:
  - name: MultiRaft
    apiVersion: v1beta1
    path: github.com/atomix/multi-raft/driver
    version: 6c700ad
  #- name: memory
  #  path: github.com/atomix/drivers/memory
  #  version: latest