# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftclusters.raft.atomix.io
spec:
  group: raft.atomix.io
  scope: Namespaced
  names:
    kind: RaftCluster
    listKind: RaftClusterList
    plural: raftclusters
    singular: raftcluster
    shortNames:
      - rc
  versions:
    - name: v1beta2
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the cluster.
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  default: 1
                image:
                  type: string
                imagePullPolicy:
                  type: string
                  enum:
                    - Never
                    - IfNotPresent
                    - Always
                imagePullSecrets:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                securityContext:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                volumeClaimTemplate:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                logging:
                  type: object
                  default: {}
                  properties:
                    encoding:
                      type: string
                      default: console
                      enum:
                        - console
                        - json
                    rootLevel:
                      type: string
                      default: info
                      enum:
                        - debug
                        - info
                        - warn
                        - error
                        - fatal
                        - panic
                    loggers:
                      type: array
                      items:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                          level:
                            type: string
                            nullable: true
                            enum:
                              - debug
                              - info
                              - warn
                              - error
                              - fatal
                              - panic
            status:
              type: object
              default: {}
              properties:
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
                lastShardID:
                  type: integer
                partitionStatuses:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - partitionID
                      - shardID
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      partitionID:
                        type: integer
                        minimum: 1
                      shardID:
                        type: integer
                        minimum: 1
      additionalPrinterColumns:
        - name: Replicas
          type: integer
          description: The number of replicas in the cluster
          jsonPath: .spec.replicas
        - name: Status
          type: string
          description: The cluster state
          jsonPath: .status.state