apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftreplicas.raft.atomix.io
spec:
  group: raft.atomix.io
  names:
    kind: RaftReplica
    listKind: RaftReplicaList
    plural: raftreplicas
    singular: raftreplica
    shortNames:
      - rm
  scope: Namespaced
  versions:
    - name: v1beta2
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - groupID
                - replicaID
                - memberID
                - pod
                - type
                - config
              properties:
                groupID:
                  type: integer
                  minimum: 1
                replicaID:
                  type: integer
                  minimum: 1
                  maximum: 1024
                memberID:
                  type: integer
                  minimum: 1
                pod:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                type:
                  type: string
                  default: Voter
                  enum:
                    - Voter
                    - Observer
                    - Witness
                join:
                  type: boolean
                peers:
                  type: integer
                config:
                  type: object
                  properties:
                    electionRTT:
                      type: integer
                      nullable: true
                    heartbeatRTT:
                      type: integer
                      nullable: true
                    snapshotEntries:
                      type: integer
                      nullable: true
                    compactionOverhead:
                      type: integer
                      nullable: true
                    maxInMemLogSize:
                      type: string
                      nullable: true
            status:
              type: object
              properties:
                podRef:
                  type: object
                  required:
                    - name
                    - uid
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    namespace:
                      type: string
                    name:
                      type: string
                    uid:
                      type: string
                version:
                  type: integer
                  nullable: true
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
                role:
                  type: string
                  enum:
                    - Follower
                    - Candidate
                    - Leader
                term:
                  type: integer
                  nullable: true
                leader:
                  type: integer
                  nullable: true
                lastUpdated:
                  type: string
                  format: date-time
                lastSnapshotIndex:
                  type: integer
                  nullable: true
                lastSnapshotTime:
                  type: string
                  format: date-time
      additionalPrinterColumns:
        - name: Replica
          type: integer
          description: The identifier of the replica
          jsonPath: .spec.replicaID
        - name: Group
          type: integer
          description: The identifier of the Raft group on which the replica is run
          jsonPath: .spec.groupID
        - name: Member
          type: integer
          description: The identifier of the Raft member on which the replica is run
          jsonPath: .spec.memberID
        - name: Pod
          type: string
          description: The pod on which the replica is run
          jsonPath: .spec.pod.name
        - name: Type
          type: string
          description: The member type
          jsonPath: .spec.type
        - name: Role
          type: string
          description: The member's current role in the Raft cluster
          jsonPath: .status.role
        - name: Leader
          type: integer
          description: The member's current leader
          jsonPath: .status.leader
        - name: Term
          type: integer
          description: The member's current term
          jsonPath: .status.term
        - name: Snapshot Index
          type: integer
          description: The index at which the member last took a snapshot
          jsonPath: .status.lastSnapshotIndex
        - name: Snapshot Time
          type: string
          description: The last time the member took a snapshot
          jsonPath: .status.lastSnapshotTime
        - name: Status
          type: string
          description: The replica state
          jsonPath: .status.state