name: Verify Helm Chart
inputs:
  working-directory:
    description: 'The working directory'
    required: true
    default: ''
runs:
  using: composite
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        check-latest: true

    - name: Set up chart tests
      uses: helm/chart-testing-action@v2.3.1

    - name: Evaluate Helm chart changes
      id: list-changed
      run: |
        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Lint Helm charts
      run: ct lint --target-branch ${{ github.event.repository.default_branch }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Create kind cluster
      uses: helm/kind-action@v1.4.0
      if: steps.list-changed.outputs.changed == 'true'

    - name: Install Helm chart
      run: ct install
      shell: bash
      working-directory: ${{ inputs.working-directory }}
