name: Check Driver Compatibility

inputs:
  path:
    description: 'The driver module path relative to the repository root'
    required: true
    default: ''

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Check module dependencies
      shell: bash
      working-directory: proxy
      run: go run github.com/atomix/atomix/proxy/cmd/atomix-build validate "../${{ inputs.path }}/go.mod"
