# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: atomix.io/v3beta3
kind: StorageProfile
metadata:
  name: {{ template "atomix-bench.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  proxy:
    {{- if .Values.proxy.image.tag }}
    image: {{ printf "%s:%s" .Values.proxy.image.repository .Values.proxy.image.tag }}
    {{- end }}
    {{- with .Values.proxy.image.pullPolicy }}
    imagePullPolicy: {{ . }}
    {{- end }}
    logging:
      rootLevel: {{ .Values.proxy.logging.rootLevel }}
      encoding: {{ .Values.proxy.logging.encoding }}
  bindings:
    - store:
        name: {{ template "atomix-bench.fullname" . }}-store