# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: atomix.io/v3beta4
kind: StorageProfile
metadata:
  name: {{ template "atomix-bench.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  routes:
    - store:
        name: {{ .Values.store.name }}
        namespace: {{ .Values.store.namespace }}