# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: atomix-shared-memory-controller
subjects:
  - kind: ServiceAccount
    name: atomix-shared-memory-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: atomix-shared-memory-controller
  apiGroup: rbac.authorization.k8s.io