name: Verify Atomix Benchmark Helm Chart

on:
  push:
    branches:
      - 'master'
    paths:
      - 'charts/atomix-bench/**'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Verify
        uses: ./.github/actions/chart/verify
        with:
          working-directory: charts/atomix-bench
