# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

replicas: 1

concurrency: 1

writePercentage: .5

numKeys: 1000

sampleInterval: 10s

store:
  name: ""
  namespace: ""

image:
  repository: atomix/bench
  tag: ""
  pullPolicy: ""
  pullSecrets: []

logging:
  rootLevel: info
  encoding: console
  loggers:
    github.com/atomix/atomix/runtime/pkg/utils/grpc/interceptors:
      level: error

proxy:
  image:
    repository: atomix/proxy
    tag: ""
    pullPolicy: ""
    pullSecrets: []

  logging:
    rootLevel: info
    encoding: console
    loggers:
      github.com/atomix/atomix/runtime/pkg/utils/grpc/interceptors:
        level: error
