# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: atomix-raft-controller-certs
type: Opaque
data:
  tls.crt: {{ .Files.Get "certs/atomix-raft-controller.crt" | b64enc }}
  tls.key: {{ .Files.Get "certs/atomix-raft-controller.key" | b64enc }}