# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test Etcd v3 Driver

on:
  push:
    branches:
      - 'master'
    tags:
      - 'drivers/etcd/v3/v*'
    paths:
      - 'drivers/etcd/v3/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test etcd@v3
        uses: ./.github/actions/go/test
        with:
          path: drivers/etcd/v3
          package: github.com/atomix/atomix/drivers/etcd/v3/driver/...
