{{- if eq .Values.store.kind "SharedMemoryStore" }}
apiVersion: sharedmemory.atomix.io/v1beta1
kind: SharedMemoryStore
metadata:
  name: {{ template "atomix-bench.fullname" . }}-store
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  image: {{ include "atomix-bench.imagename" .Values.store.memory.image | quote }}
  {{- with .Values.store.memory.image.pullPolicy }}
  imagePullPolicy: {{ . }}
  {{- end }}
  logging:
    rootLevel: {{ .Values.store.memory.logging.rootLevel }}
    encoding: {{ .Values.store.memory.logging.encoding }}
{{- end }}