apiVersion: atomix.io/v3beta3
kind: StorageProfile
metadata:
  name: {{ template "atomix-bench.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  proxy:
    image: {{ include "atomix-bench.imagename" .Values.proxy.image | quote }}
    {{- with .Values.proxy.image.pullPolicy }}
    imagePullPolicy: {{ . }}
    {{- end }}
    logging:
      rootLevel: {{ .Values.proxy.logging.rootLevel }}
      encoding: {{ .Values.proxy.logging.encoding }}
  bindings:
    - store:
        name: {{ template "atomix-bench.fullname" . }}-store