apiVersion: atomix.io/v3beta3
kind: StorageProfile
metadata:
  name: {{ template "atomix-bench.fullname" . }}
spec:
  proxy:
    {{- if .Values.proxy.image.tag }}
    image: {{ include "atomix-bench.imagename" .Values.proxy.image | quote }}
    {{- end }}
    {{- with .Values.proxy.image.pullPolicy }}
    imagePullPolicy: {{ . }}
    {{- end }}
    logging:
      rootLevel: {{ .Values.proxy.logging.rootLevel }}
      encoding: {{ .Values.proxy.logging.encoding }}
  bindings:
    - store:
        name: {{ template "atomix-bench.fullname" . }}