name: Build and Test Store | PodMemory

on:
  push:
    branches:
      - 'master'
    paths:
      - 'stores/pod-memory/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Tests
        working-directory: stores/pod-memory
        run: make test