name: Build and Test Bench

on:
  push:
    branches:
      - 'master'
    paths:
      - 'bench/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Tests
        working-directory: bench
        run: make test