name: Publish Helm Chart | Atomix Bench

on:
  push:
    branches:
      - 'master'
    paths:
      - 'charts/atomix-bench/**'

jobs:
  publish-helm-chart:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish Helm Chart
        run: |-
          docker run -i \
            -v `pwd`:/build -w /build \
            -e GITHUB_TOKEN=${{ secrets.GH_TOKEN }} \
            --entrypoint ./build/release \
            quay.io/helmpack/chart-releaser:v1.4.0 \
            atomix-bench