name: Publish Atomix Helm Chart

on:
  workflow_run:
    workflows:
      - "Verify Atomix Helm Chart"
    branches:
      - master
    types:
      - completed
  push:
    branches:
      - 'master'
    paths:
      - 'charts/atomix/**'

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish Helm chart
        run: |-
          docker run -i \
            -v `pwd`:/build -w /build \
            -e GITHUB_TOKEN=${{ secrets.GH_TOKEN }} \
            --entrypoint ./build/release \
            quay.io/helmpack/chart-releaser:v1.4.0 \
            atomix