name: release

on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:
  release-controller:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Release Environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GH_TOKEN}}' > .release-env
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Release
        working-directory: controller
        run: make release
  release-proxy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Release Environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GH_TOKEN}}' > .release-env
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Release
        working-directory: proxy
        run: make release