# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

replicas: 1

image:
  registry: ""
  repository: atomix/controller
  # TODO: Set image tag to release version
  tag: latest
  # TODO: Revert pull policy to default for patch releases or Always for for minor releases
  pullPolicy: IfNotPresent
  pullSecrets: []

init:
  image:
    registry: ""
    repository: atomix/controller-init
    # TODO: Set image tag to release version
    tag: latest
    # TODO: Revert pull policy to default for patch releases or Always for for minor releases
    pullPolicy: IfNotPresent
    pullSecrets: []

proxy:
  image:
    registry: ""
    repository: atomix/proxy
    # TODO: Set image tag to release version
    tag: latest
    # TODO: Revert pull policy to default for patch releases or Always for for minor releases
    pullPolicy: IfNotPresent
    pullSecrets: []
