# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

replicas: 1

image:
  registry: ""
  repository: atomix/controller
  tag: v0.7.7
  pullPolicy: Always
  pullSecrets: []

init:
  image:
    registry: ""
    repository: atomix/controller-init
    tag: v0.7.7
    pullPolicy: Always
    pullSecrets: []

proxy:
  image:
    registry: ""
    repository: atomix/proxy
    tag: v0.12
    pullPolicy: Always
    pullSecrets: []
