name: Publish Helm Chart

inputs:
  path:
    description: 'The chart path relative to the repository root'
    required: true
    default: ''

  token:
    description: 'The GitHub token for the release repository'
    required: true
    default: ''

runs:
  using: composite
  steps:
    - name: Publish Helm chart
      shell: bash
      run: |-
        docker run -i \
          -v `pwd`:/build -w /build \
          -e GITHUB_TOKEN=${{ inputs.token }} \
          --entrypoint ./.github/scripts/release-chart \
          quay.io/helmpack/chart-releaser:v1.4.0 \
          ${{ inputs.path }}